version: "3.8"
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # создаём таблицы БД
      - ./data.sql:/docker-entrypoint-initdb.d/load_data.sql # загружаем данные в таблицы
      - ./quest.sql:/docker-entrypoint-initdb.d/queries.sql # выполняем запросы к БД
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "username", "library_db"]
      interval: 5s
      retries: 5
    restart: always
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    depends_on:
      - postgres
    ports:
      - "8123:8123"
    volumes:
      - ./clickhouse_data/migrate.sql:/docker-entrypoint-initdb.d/migrate.sql 